#!/bin/sh
set -e

USER_NAME="asl-parrot"

# Create user if it doesn't exist
if ! getent passwd "${USER_NAME}" >/dev/null; then
    adduser --system \
        --no-create-home \
        --disabled-password \
        --gecos "ASL Parrot Application User" "${USER_NAME}"
fi

# Because we're dropping in new/updated .service files:
deb-systemd-invoke daemon-reload 

# Optional: Set permissions or ownership for directories/files if needed
# chown -R "${USER_NAME}:${GROUP_NAME}" /var/lib/myapp
